language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox

install: pip install -r requirements_test.txt
script: pytest  --cov-report term --cov=py_casim tests/
after_success: codecov

deploy:
  install: pip install -r requirements_dev.txt
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: cKCkZWTT+jCVlTwtJcqAMdzgpoMZVXW+eQzRlBvsz9g8H8TOtH9E91kVAde3gqggERGrgeWjrX+y1bloFNJ0fYm+v5qyPMF4uqXO2vm5xljV8qJ1QFe0D7/va2oGEG3LHqRC0/VMhdFf4QnK0MNLTR9rnOOQVWz9KNsjfZ4myawt9aD22SxUqjCg91HPgNHdMZB0A4H+zqh+yepUKS79FoVzOAO8R/i0JQlkzuy2l1JA0PL8yJ3jU9ggERq0bc8zJN3kAH19bPvVC9Vl3JM58oaHLngzW5zgf5gLRocG4H0GsXxqKeCT/svmsL+8pGn6QEbmJ/N+Z94qnCb62y7gSpX/OwfCrrSZNHiJibegA5rEyo20KUuwv1qAWycBuxPqb5NjBp2nzuxCfaSQKSnFP1tYcARJ+7mY6PcZ3YSQK8cT0eP6ucRBrwGJeXCovciSyI6rCAvTJRnzgzd6CvXkEmu/WyyxE5aBwnN8F8DGHrKLQjUzSbrfBMjhYkiFsYyeaqo1GQmH37uVs7shCUmlN4OSSfwAfEsdK34wrKcPE6yGz+VtkvfJZg+i7L/oGbY50PKXe6ao2VptQ/irI7p4rdEn0Qy2vZuKFWleIl/BtGb5t7pdevtfiMD/U7MIzgzL162pwu0edcir7SeOA1T83f+7ZZOUeoBi4OBAEmUlU5g=
  on:
    tags: true
    python: 3.7